"""
Generates SecretsBridge_generated.h from environment secrets.

Run at build time (pre-CMake or from Gradle). Reads TIDAL_API_KEY,
TIDAL_BASE_URL, PROVIDER_MODULE_KEY, RELEASE_CERT_SHA256 from environment /
.env, splits keys into random-length XOR'd fragments, and writes a C header.
The header is .gitignored — GitHub only has the template SecretsBridge.cpp,
never the actual key bytes.

Usage:
    python tools/generate_native_secrets.py
"""

import base64
import os
import random


def resolve_env(name: str) -> str:
    val = os.environ.get(name, "").strip()
    if val:
        return val
    if os.path.isfile(".env"):
        with open(".env", "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith(f"{name}="):
                    return line.split("=", 1)[1].strip()
    return ""

API_KEY = resolve_env("KEY") or resolve_env("URL_SECRET")
BASE_URL = resolve_env("URL") or resolve_env("BASE_URL")
CERT_SHA256 = resolve_env("RELEASE_CERT_SHA256") or "PLACEHOLDER_REPLACE_WITH_YOUR_CERT_SHA256"
MODULE_KEY_B64 = resolve_env("PROVIDER_MODULE_KEY")

if not API_KEY:
    print("WARNING: URL_SECRET not set. Native secrets will be empty (YouTube fallback).")

if not MODULE_KEY_B64:
    print("WARNING: PROVIDER_MODULE_KEY not set. Native module key will be empty (addons rejected).")

def generate_fragments(key: str, num_fragments: int = 8) -> list:
    """Split key into num_fragments pieces, each XOR'd with a random mask."""
    if not key:
        return []
    chunk_size = max(1, len(key) // num_fragments)
    chunks = []
    for i in range(0, len(key), chunk_size):
        chunks.append(key[i:i + chunk_size])

    fragments = []
    for chunk in chunks:
        mask = random.randint(0x10, 0xFE)  # avoid 0x00 and 0xFF
        xored = [b ^ mask for b in chunk.encode("latin1")]
        fragments.append((xored, mask, len(chunk)))
    return fragments

def resolve_module_key_bytes() -> bytes:
    """Return 32B module key or b'' when not provisioned."""
    if not MODULE_KEY_B64:
        return b""
    s = MODULE_KEY_B64.strip()
    try:
        decoded = base64.b64decode(s)
        if len(decoded) == 32:
            return decoded
    except Exception:
        pass
    raw = s.encode("latin1")
    if len(raw) == 32:
        return raw
    print(f"WARNING: PROVIDER_MODULE_KEY invalid (need b64 of 32B, got {len(s)} chars). Empty.")
    return b""

def generate_byte_fragments(data: bytes, num_fragments: int = 8) -> list:
    if not data:
        return []
    chunk_size = max(1, len(data) // num_fragments)
    fragments = []
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i + chunk_size]
        mask = random.randint(0x10, 0xFE)
        xored = [b ^ mask for b in chunk]
        fragments.append((xored, mask, len(chunk)))
    return fragments

fragments = generate_fragments(API_KEY)
module_key = resolve_module_key_bytes()
module_fragments = generate_byte_fragments(module_key) if module_key else []

# Generate header
lines = []
lines.append("// AUTO-GENERATED — DO NOT COMMIT TO VERSION CONTROL")
lines.append("// Generated by tools/generate_native_secrets.py")
lines.append("#pragma once")
lines.append("#include <cstdint>")
lines.append("")
lines.append(f'constexpr char EXPECTED_CERT_PREFIX[] = "{CERT_SHA256}";')
lines.append("")

url_fragments = generate_fragments(BASE_URL)

# Base URL fragments (dynamic XOR, never plain string in .rodata)
lines.append(f"static constexpr int URL_FRAGMENT_COUNT = {len(url_fragments)};")
lines.append("")
for i, (xored_bytes, mask, length) in enumerate(url_fragments):
    hex_vals = ",".join(f"0x{b:02X}" for b in xored_bytes)
    lines.append(f"static const uint8_t U{i}[] = {{{hex_vals}}};")
lines.append("")

lines.append("struct Fragment {")
lines.append("    const uint8_t* data;")
lines.append("    uint8_t        len;")
lines.append("    uint8_t        mask;")
lines.append("};")
lines.append("")
lines.append("static const Fragment URL_FRAGMENTS[] = {")
for i, (xored_bytes, mask, length) in enumerate(url_fragments):
    lines.append(f"    {{U{i}, {length}, 0x{mask:02X}}},")
lines.append("};")
lines.append("")

# Tidal API key fragments
lines.append(f"static constexpr int FRAGMENT_COUNT = {len(fragments)};")
lines.append("")
for i, (xored_bytes, mask, length) in enumerate(fragments):
    hex_vals = ",".join(f"0x{b:02X}" for b in xored_bytes)
    lines.append(f"static const uint8_t F{i}[] = {{{hex_vals}}};")
lines.append("")
lines.append("static const Fragment FRAGMENTS[] = {")
for i, (xored_bytes, mask, length) in enumerate(fragments):
    lines.append(f"    {{F{i}, {length}, 0x{mask:02X}}},")
lines.append("};")
lines.append("")

# Provider module key fragments (binary 32B, scattered, per-build random masks)
lines.append(f"static constexpr int MODULE_FRAGMENT_COUNT = {len(module_fragments)};")
lines.append("")
for i, (xored_bytes, mask, length) in enumerate(module_fragments):
    hex_vals = ",".join(f"0x{b:02X}" for b in xored_bytes)
    lines.append(f"static const uint8_t M{i}[] = {{{hex_vals}}};")
lines.append("")
lines.append("static const Fragment MODULE_FRAGMENTS[] = {")
for i, (xored_bytes, mask, length) in enumerate(module_fragments):
    lines.append(f"    {{M{i}, {length}, 0x{mask:02X}}},")
lines.append("};")
lines.append("")

header_content = "\n".join(lines) + "\n"

out_path = os.path.join("app", "src", "main", "cpp", "SecretsBridge_generated.h")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    f.write(header_content)

print(f"Generated {out_path}")
print(f"  Base URL: {BASE_URL if BASE_URL else '[EMPTY]'}")
print(f"  URL secret: {'[' + str(len(API_KEY)) + ' chars]' if API_KEY else '[EMPTY]'}")
print(f"  Module key: {'[32B OK]' if module_key else '[EMPTY]'}")
print(f"  Fragments: {len(url_fragments)} url, {len(fragments)} secret, {len(module_fragments)} module")
print(f"  Cert prefix: {CERT_SHA256[:20]}...")

# Verify reconstruction
if BASE_URL:
    reconstructed_url = ""
    for xored_bytes, mask, _ in url_fragments:
        for b in xored_bytes:
            reconstructed_url += chr(b ^ mask)
    assert reconstructed_url == BASE_URL, "Base URL reconstruction mismatch"
    print("  Base URL verification: PASS")
if API_KEY:
    reconstructed = ""
    for xored_bytes, mask, _ in fragments:
        for b in xored_bytes:
            reconstructed += chr(b ^ mask)
    assert reconstructed == API_KEY, "URL secret reconstruction mismatch"
    print("  URL secret verification: PASS")
if module_key:
    recon = bytearray()
    for xored_bytes, mask, _ in module_fragments:
        for b in xored_bytes:
            recon.append(b ^ mask)
    assert bytes(recon) == module_key, "Module key reconstruction mismatch"
    print("  Module verification: PASS")
